# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `acts_as_tenant` gem.
# Please instead update this file by running `bin/tapioca gem acts_as_tenant`.


# pkg:gem/acts_as_tenant#lib/acts_as_tenant/version.rb:1
module ActsAsTenant
  class << self
    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:47
    def add_global_record_model(model); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:31
    def configuration; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:25
    def configure; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:67
    def current_tenant; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:63
    def current_tenant=(tenant); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:91
    def default_tenant; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:22
    def default_tenant=(_arg0); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:51
    def fkey; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:43
    def models_with_global_records; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:95
    def mutable_tenant!(toggle); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:99
    def mutable_tenant?; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:55
    def pkey; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:59
    def polymorphic_type; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:35
    def set_tenant_klass(klass); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:143
    def should_require_tenant?; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:39
    def tenant_klass; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:75
    def test_tenant; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:71
    def test_tenant=(tenant); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:83
    def unscoped; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:79
    def unscoped=(unscoped); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:87
    def unscoped?; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:136
    def with_mutable_tenant(&block); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:103
    def with_tenant(tenant, &block); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:116
    def without_tenant(&block); end
  end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/active_job_extensions.rb:2
module ActsAsTenant::ActiveJobExtensions
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/active_job_extensions.rb:7
  def deserialize(job_data); end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/active_job_extensions.rb:3
  def serialize; end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:2
class ActsAsTenant::Configuration
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:13
  def job_scope; end

  # Used for looking job tenants in background jobs
  #
  # Format matches Rails scopes
  #
  #   job_scope = ->(relation) {}
  #   job_scope = -> {}
  #
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:23
  def job_scope=(scope); end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:9
  def pkey; end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:3
  def pkey=(_arg0); end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:5
  def require_tenant; end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/configuration.rb:3
  def require_tenant=(_arg0); end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions.rb:2
module ActsAsTenant::ControllerExtensions
  # this method allows setting the current_tenant by reading the subdomain and looking
  # it up in the tenant-model passed to the method. The method will look for the subdomain
  # in a column referenced by the second argument.
  #
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions.rb:10
  def set_current_tenant_by_subdomain(tenant = T.unsafe(nil), column = T.unsafe(nil), subdomain_lookup: T.unsafe(nil)); end

  # 01/27/2014 Christian Yerena / @preth00nker
  # this method adds the possibility of use the domain as a possible second argument to find
  # the current_tenant.
  #
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions.rb:21
  def set_current_tenant_by_subdomain_or_domain(tenant = T.unsafe(nil), primary_column = T.unsafe(nil), second_column = T.unsafe(nil), subdomain_lookup: T.unsafe(nil)); end

  # This method sets up a method that allows manual setting of the current_tenant. This method should
  # be used in a before_action. In addition, a helper is setup that returns the current_tenant
  #
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions.rb:32
  def set_current_tenant_through_filter; end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/filter.rb:3
module ActsAsTenant::ControllerExtensions::Filter
  extend ::ActiveSupport::Concern

  private

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/filter.rb:8
  def set_current_tenant(current_tenant_object); end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/subdomain.rb:3
module ActsAsTenant::ControllerExtensions::Subdomain
  extend ::ActiveSupport::Concern

  private

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/subdomain.rb:13
  def find_tenant_by_subdomain; end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/subdomain_or_domain.rb:3
module ActsAsTenant::ControllerExtensions::SubdomainOrDomain
  extend ::ActiveSupport::Concern

  private

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/controller_extensions/subdomain_or_domain.rb:13
  def find_tenant_by_subdomain_or_domain; end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:17
class ActsAsTenant::Current < ::ActiveSupport::CurrentAttributes
  class << self
    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def acts_as_tenant_unscoped; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def acts_as_tenant_unscoped=(value); end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def current_tenant; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def current_tenant=(value); end

    private

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def __class_attr_defaults; end

    # pkg:gem/acts_as_tenant#lib/acts_as_tenant.rb:18
    def __class_attr_defaults=(new_value); end
  end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/errors.rb:2
class ActsAsTenant::Error < ::StandardError; end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/errors.rb:5
module ActsAsTenant::Errors; end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/errors.rb:6
class ActsAsTenant::Errors::ModelNotScopedByTenant < ::ActsAsTenant::Error; end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/errors.rb:9
class ActsAsTenant::Errors::NoTenantSet < ::ActsAsTenant::Error; end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/errors.rb:12
class ActsAsTenant::Errors::TenantIsImmutable < ::ActsAsTenant::Error; end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/model_extensions.rb:2
module ActsAsTenant::ModelExtensions
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActsAsTenant::ModelExtensions::ClassMethods
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/model_extensions.rb:5
module ActsAsTenant::ModelExtensions::ClassMethods
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/model_extensions.rb:6
  def acts_as_tenant(tenant = T.unsafe(nil), scope = T.unsafe(nil), **options); end

  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/model_extensions.rb:108
  def validates_uniqueness_to_tenant(fields, args = T.unsafe(nil)); end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/tenant_helper.rb:2
module ActsAsTenant::TenantHelper
  # pkg:gem/acts_as_tenant#lib/acts_as_tenant/tenant_helper.rb:3
  def current_tenant; end
end

# pkg:gem/acts_as_tenant#lib/acts_as_tenant/version.rb:2
ActsAsTenant::VERSION = T.let(T.unsafe(nil), String)
