plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "sorbet/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    # Dados de seed (strings longas de conteúdo)
    - "db/seeds.rb"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "app/services/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "app/services/**/*"
    - "db/seeds.rb"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "db/seeds.rb"

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
